services:
  garage:
    image: dxflrs/garage:v0.9.3
    container_name: garage
    restart: unless-stopped
    environment:
      GARAGE_ADMIN_TOKEN: ${GARAGE_ADMIN_TOKEN}
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./configs/garage.toml:/etc/garage.toml
      - ./.garage/meta:/var/lib/garage/meta
      - ./.garage/data:/var/lib/garage/data
    networks:
      - keycloak_network

  memcached:
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"
    command: memcached --port=11211 --memory-limit=64 --conn-limit=1024 --threads=4 # 64 -> 64MB memory limit
    restart: unless-stopped
    networks:
      - keycloak_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass your_password_here --appendonly yes
    restart: unless-stopped
    networks:
      - keycloak_network

  postgres:
    image: postgres:16.2
    container_name: postgres-keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloack
    command: start
    environment:
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

  rest-server:
    image: file-storage-rest
    container_name: rest-server
    build:
      context: backend/
      dockerfile: rest.Dockerfile
    ports:
      - 4444:4444
    networks:
      - keycloak_network
    depends_on:
      - redis
      - memcached
      - grpc-server
      - keycloak

  grpc-server:
    image: file-storage-grpc
    container_name: grpc-server
    build:
      context: backend/
      dockerfile: grpc.Dockerfile
    ports:
      - 50051:50051
    environment:
      GARAGE_SECRET_KEY: ${GARAGE_SECRET_KEY}
      GARAGE_KEY_ID: ${GARAGE_KEY_ID}
    networks:
      - keycloak_network
    depends_on:
      - garage
      - keycloak
      - jaeger

  frontend:
    image: file-storage-frontend
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 5173:80
    networks:
      - keycloak_network
    depends_on:
      - keycloak
      - rest-server

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - keycloak_network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - keycloak_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./.qdrant/data:/qdrant/storage
    networks:
      - keycloak_network

volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
